- public/static/images/icons/play1.svg
- public/static/images/icons/play2.svg
- src/views/pages/HomeView/WatchVideos.js
- src/views/pages/HomeView/index.js
Fixes Issue #26 
Colors are according to the original figma design, please tell me if there are some changes in it.
> Issue #26: Add Watch Our Videos View

- src/views/pages/HomeView/HomeViewData.js
- src/views/pages/HomeView/MainCards.js
- src/views/pages/HomeView/WhatWeStandFor.js
- src/views/pages/HomeView/index.js
It was little hard to dig through the unnecessary data to visit the actual code.
Moved all the data inside `HomeView` to a seperate file for better code visibility.
> [Refractor 1] move data to seperate files for better code visibility

- src/components/AboutCard/MainCard.js
- src/components/AboutCard/SubCard.js
@KeenWarrior please review.
checked responsive behaviour on all screens
> add responsive standfor page to show fullly aligned contents on md and sm screens.

- package-lock.json
- package.json
- src/views/pages/HomeView/Events.js
- src/views/pages/HomeView/HomeViewData.js
- src/views/pages/HomeView/Testimonials/TestimonialCard.js
- src/views/pages/HomeView/Testimonials/index.js
- src/views/pages/HomeView/index.js
Created a new folder src/views/HomeView/**Testimonials** having the card layout and an index.js file to map through the data in src/views/HomeViewData.js to show the testimonials. #28 
Side note :- I did a last minute change to make the alternate name dynamic in case there's no picture for the avatar which caused a merge conflict. Maybe this will help in resolving it. **File :-** src/views/HomeView/Testimonials/TestimonialCard.js **Line :-** 45
> Added testimonials section

- src/data/courses/advanced/CompetitiveJava.js
> Added Competitive Programming in Java course content

- public/index.html
- src/layouts/MainLayout/TopBar/index.js
- src/theme/typography.js
> Add Montserrat Font

- src/layouts/MainLayout/TopBar/Account.js
- src/layouts/MainLayout/TopBar/index.js
- src/reducers/accountReducer.js
Closes #75 
Added Circular Bar till the user is confirmed to be logged in / Not.
*See the effect on refreshing the browser again and again.*
> Add Circular Progress till the Firebase Data is fetched

- src/views/pages/ApplicationsView/ApplicationSteps.js
- src/views/pages/CLView/ApplyNowModal.js
Dynamically change the remaining number of characters required.
Issue : #81
> Dynamically change the remaining number of characters required.

- public/index.html
- src/App.js
- src/layouts/MainLayout/TopBar/index.js
> Add hello-bar to website

- package-lock.json
- src/App.js
- src/Routes.js
Now tapping on any random URL, user will be routed to the 404 page.
Issue : #89
> Added route to 404 Page

- src/Routes.js
- src/views/pages/documents/privacyView/index.js
- src/views/pages/documents/refundView/index.js
- src/views/pages/documents/termsView/index.js
> Setup Route to Privacy, terms and conditions and refund policies in footer

- src/components/Hero/HeroWithLogo.js
- src/layouts/MainLayout/TopBar/Account.js
- src/layouts/MainLayout/TopBar/LoginDialog.js
- src/layouts/MainLayout/TopBar/index.js
- src/views/pages/HomeView/Hero.js
Fixes #101, #104 
Also fixes hero page of homeview:
Earlier: (on smaller screens)
[see overlapped hero image (before)](https://user-images.githubusercontent.com/48255244/94449631-ed867b80-01c9-11eb-8728-68b9f66ef133.png)
> fixed login button covering the  cfc title and home-view hero page

- README.md
- Added Discord badge in README which links to dedicated channel for
development of this website
- Fixed typographical errors in README
- Removed broken links from README #108
Closes #108
> [docs] Updated README

- src/views/pages/common/Apply.js
Made changes in Apply.js so that it becomes responsive
before :
after :
> Solved issue #115 Made changes in Apply.js so that it becomes responsive

- src/views/pages/Courses/Schedule.js
- src/views/pages/Courses/partials/FAQuestions.js
- src/views/pages/common/Apply.js
#80 fixed , now the card is collapsing on clicking the "^" button
> card collapsing fixed in course and faq card

- src/Routes.js
Partial fix   : #95 
Tried fixing scroll reset problem identified at #95
> Fixing scroll reset problem

- src/data/HomeViewData/HomeViewData.js
> Small typo in contributors

- src/services/authService.js
Removed line to console log firebase auth token.
> Fixed issue #123

- src/views/pages/common/Recommendations.js
- src/views/pages/common/index.css
customized the scrollbar as per #119 issue
> scrollbar css changed

- public/index.css
- src/Routes.js
- src/data/blogAuthors.js
- src/views/pages/BlogsView/Blog/BLogContent.js
- src/views/pages/BlogsView/Blog/Blog.js
- src/views/pages/BlogsView/Blog/BlogCard.js
- src/views/pages/BlogsView/Blog/index.js
- src/views/pages/BlogsView/BlogContent.js
- src/views/pages/BlogsView/BlogHead.js
- src/views/pages/BlogsView/BlogItem.js
- src/views/pages/BlogsView/SideBar.js
- src/views/pages/BlogsView/index.js
> Automate Blog page to fetch all the data from axios and render medium Articles

- .prettierrc
- src/data/CourseFeatures.js
- src/views/pages/Course/Features.js
- src/views/pages/Course/ProcessSteppers.js
- src/views/pages/Course/partials/Topics.js
- src/views/pages/HomeView/Courses.js
Things Done: 
- Fix white horizontal line on course page
- Align Topics dropDown on coursePage
- Make courses come closer for wide screens.
> Web Style fixes

- README.md
Added telegram twitter and good first issue badge on readme.
> add social badges to readme

- src/Routes.js
Fixed scroll reset issues with pages
Fixes #95
> Fix scrolling issues when going to different pages

- package-lock.json
- package.json
- src/assets/css/swiper-styles.css
- src/components/Event/EventCard.js
- src/views/pages/EventsView/Events.js
- src/views/pages/HomeView/Events.js
> Add Slider in event in Homepage and circular progress bar when loading

- src/views/pages/HomeView/Promoters.js
> remove ms logo

- src/views/pages/Course/CTA.js
(One copy of same PR is made against master to avoid any conflicts)
before: 
after:
> [Dev] change consultation form design

- src/views/pages/CoursesView/Courses.js
> Add training course to courses View.

- src/views/pages/CLView/StandFor.js
* dark mode problems on mac
* Update Success.js
* minor: spelling correction
> minor: spelling correcction in CL view (#189)

- src/components/Course/CourseCardTemplate1.js
- src/data/courses/advanced/CompetitiveJava.js
- src/data/courses/advanced/MachineLearning.js
- src/data/courses/advanced/WebDevelopment.js
- src/data/courses/foundation/AlgoJS.js
- src/data/courses/foundation/AlgoJava.js
- src/data/courses/foundation/AlgoPython.js
- src/data/courses/foundation/DevPython.js
- src/data/courses/training/CompetitiveJava.js
- src/data/courses/training/MachineLearning.js
- src/data/courses/training/WebDevelopment.js
- src/views/pages/Course/Schedule.js
- src/views/pages/Course/partials/Details.js
- src/views/pages/Course/partials/DetailsBottom.js
Change in course template structure.
Adding more courses in schedules.
> Change Course template structure, add upcoming courses

- src/components/Course/CourseCardTemplate1.js
- src/data/courses/advanced/CompetitiveJava.js
- src/data/courses/advanced/MachineLearning.js
- src/data/courses/advanced/WebDevelopment.js
- src/data/courses/foundation/AlgoJS.js
- src/data/courses/foundation/AlgoJava.js
- src/data/courses/foundation/AlgoPython.js
- src/data/courses/foundation/DevPython.js
- src/data/courses/training/CompetitiveJava.js
- src/data/courses/training/MachineLearning.js
- src/data/courses/training/WebDevelopment.js
- src/views/pages/Course/Schedule.js
- src/views/pages/Course/partials/Details.js
- src/views/pages/Course/partials/DetailsBottom.js
* Change Course template structure, add upcoming courses
* Revision 1: added brackets and reverted duration key
> Change Course template structure, add upcoming courses (#207)

- src/services/authService.js
only edited the auth service file, removed the firebase warning
> fixed the firebase warning in the browser dev console

- src/components/auth/Auth.js
- src/services/authService.js
added a type check before accessing the user token to remove the error
> fixed Cannot read property 'getIdToken' of null

- src/views/pages/HireWithUsView/Developer/DevBox/index.js
- src/views/pages/HireWithUsView/Developer/Developer.js
> Responsive Development Component

- package-lock.json
- src/components/popups/autoPopupDialog.js
- src/views/pages/Course/ApplyModal.js
- src/views/pages/Course/CoursePage/index.js
- src/views/pages/Course/Features.js
- src/views/pages/Course/FinalAction.js
- src/views/pages/Course/Major.js
- src/views/pages/Course/Schedule.js
- src/views/pages/Course/partials/Details.js
- src/views/pages/Course/partials/DetailsBottom.js
- src/views/pages/Course/partials/FAQuestions.js
- src/views/pages/Course/partials/Overview.js
- src/views/pages/Course/partials/Projects.js
- src/views/pages/Course/partials/Topics.js
> Console Errors for Course Page fixed
